### PR TITLE
OCPBUGS-36078: UPSTREAM: <carry>: Fix go-retryablehttp CVE - 4.15

### PR DESCRIPTION
**Pull request by Karthik-K-N**

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by sunzhaohua2** [comment]
@Karthik-K-N sure, I will verify the 4.16 bug, then dev will add backport-risk-assessed label for this pr, and then I will add cherry-pick-approve label.

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N sure, I will verify the 4.16 bug, then dev will add backport-risk-assessed label for this pr, and then I will add cherry-pick-approve label.

sure thanks

**Comment by Karthik-K-N** [comment]
@JoelSpeed Can I get other required labels. Thanks

**Comment by Karthik-K-N** [comment]
since Joel is on vacation @damdo can you help us with the labels or should I wait?

**Review by damdo — COMMENTED** [review]
/approve
/lgtm

**Comment by JoelSpeed** [comment]
Manually checked the bug requirements, bug is private and so cannot be read by the bot

**Comment by Karthik-K-N** [comment]
Since build is available I think we can proceed to test 4.14?

**Comment by damdo** [comment]
Yes @Karthik-K-N SGTM

**Pull request merged**
