### PR TITLE
OCPBUGS-22604,OCPCLOUD-2454: Merge https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud:v0.7.0 (e51c61e) into main

### PR DESCRIPTION
**Pull request by damdo**

### CODE REVIEW

**Comment by damdo** [comment]
@Karthik-K-N Hey would you mind testing this PR (in combo with the [core CAPI one](https://github.com/openshift/cluster-api/pull/192)) for me once you are back from your vacations? Thanks!

**Comment by Karthik-K-N** [comment]
> /hold Waiting for Karthink's manual test results

Thank you, 
Will update here once test is done.

**Comment by theobarberbany** [comment]
/retitle OCPBUGS-22604,OCPCLOUD-2454: Merge https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud:v0.7.0 (e51c61e) into main

**Review by Karthik-K-N — COMMENTED** [review]
Verified on cluster and everything works as expected, Here are the results

```
$ make e2e


Ran 1 of 3 Specs in 1264.367 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 2 Skipped
PASS

Ginkgo ran 1 suite in 21m18.839853073s
Test Suite Passed
```

```
karthikkn@Karthiks-MacBook-Pro ~ % oc -n openshift-cluster-api get machines
NAME                          CLUSTER                       NODENAME                         PROVIDERID                                                                                         PHASE     AGE   VERSION
ibmpowervs-machineset-qsh8j   rdr-ocp-qe-ipi-415rc1-hcps7   powervs-machine-template-hfz6f   ibmpowervs://dal/dal10/d62c6db1-abcb-43b6-8b3a-c7394e2378e4/f0f386eb-3ff8-48d4-9566-c0acd77f5be4   Running   19m
karthikkn@Karthiks-MacBook-Pro ~ % oc get nodes
NAME                                       STATUS     ROLES                  AGE   VERSION
powervs-machine-template-hfz6f             Ready   worker                 3m27s   v1.28.4+7aa0a74
rdr-ocp-qe-ipi-415rc1-hcps7-master-0       Ready      control-plane,master   9d    v1.28.4+7aa0a74
rdr-ocp-qe-ipi-415rc1-hcps7-master-1       Ready      control-plane,master   9d    v1.28.4+7aa0a74
rdr-ocp-qe-ipi-415rc1-hcps7-master-2       Ready      control-plane,master   9d    v1.28.4+7aa0a74
rdr-ocp-qe-ipi-415rc1-hcps7-worker-4b9jx   Ready      worker                 9d    v1.28.4+7aa0a74
rdr-ocp-qe-ipi-415rc1-hcps7-worker-8xp8p   Ready      worker                 9d    v1.28.4+7aa0a74
rdr-ocp-qe-ipi-415rc1-hcps7-worker-b4xgz   Ready      worker                 9d    v1.28.4+7aa0a74
```

**Review by Karthik-K-N — APPROVED** [review]
/lgtm

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
