### PR TITLE
OCPBUGS-12615: Update IBM Packages

### PR DESCRIPTION
**Pull request by Karthik-K-N**
Updating IBM packages to fix vulnerabilities

CVE - https://pkg.go.dev/vuln/GO-2023-1571

Fixes: https://issues.redhat.com/browse/OCPBUGS-12615

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
is this a cherry-pick? Has this been fixed in the master branch already?

**Comment by mkumatag** [comment]
> is this a cherry-pick? Has this been fixed in the master branch already?

yes via https://github.com/openshift/cluster-api-provider-ibmcloud/pull/54

**Pull request merged**
