### PR TITLE
Bug 2067844: Update dependencies to K8s 1.24, go 1.18

### PR DESCRIPTION
**Pull request by damdo**
- Update the dependencies to K8s 1.24.
- Bump project to go 1.18.

### CODE REVIEW

**Comment by Fedosin** [comment]
/retitle Bug 2067844: Update dependencies to K8s 1.24, go 1.18

**Comment by JoelSpeed** [comment]
/lgtm
/approve

Having scanned the test results, I think this is fine, the issues look unrelated and appear to be permanent issues with the IBM e2e results

**Pull request merged**
