### PR TITLE
OCPBUGS-43686: UPSTREAM: <carry>: Fix go-retryablehttp CVE - 4.16

### PR DESCRIPTION
**Pull request by Karthik-K-N**

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
4.17 PR has been merged and included in the [build](https://github.com/openshift/cluster-api-provider-ibmcloud/pull/86#issuecomment-2436785518), so any help here
@sunzhaohua2

**Comment by JoelSpeed** [comment]
/lgtm
/approve
/label backport-risk-assessed

Waiting on 4.17 patch to go through QE before adding Jira labels

**Comment by Karthik-K-N** [comment]
> /lgtm /approve /label backport-risk-assessed
> 
> Waiting on 4.17 patch to go through QE before adding Jira labels

4.17 bug moved into verfied state https://issues.redhat.com/browse/OCPBUGS-37369

**Comment by JoelSpeed** [comment]
Ready fro QE to take a look now then

**Comment by Karthik-K-N** [comment]
PR changes has been included in build , Looking forward for help in subsequent PRs to other branches https://github.com/openshift/cluster-api-provider-ibmcloud/pull/87

**Comment by sunzhaohua2** [comment]
Sorry, not sure why pr merged but bug is still in Post status, I will verify this 4.16 bug.

**Comment by Karthik-K-N** [comment]
> Sorry, not sure why pr merged but bug is still in Post status, I will verify this 4.16 bug.

No Problem, Thank you. We wanted to close all the CVE PRs so seeking help.

**Pull request merged**
