### PR TITLE
Merge https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud:v0.5.1 (d1ced87) into main

### PR DESCRIPTION
**Pull request by damdo**

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
Tested the changes along with capi-operator changs:  https://github.com/openshift/cluster-capi-operator/pull/118 and e2e tests are passing

```
karthikkn@Karthiks-MacBook-Pro capi-test % oc -n openshift-cluster-api get coreprovider
NAME          INSTALLEDVERSION   READY
cluster-api   v1.4.2             True
```


```
karthikkn@Karthiks-MacBook-Pro capi-test % oc -n openshift-cluster-api get infrastructureprovider
NAME       INSTALLEDVERSION   READY
ibmcloud   v0.5.1             True

```

```
karthikkn@Karthiks-MacBook-Pro cluster-capi-operator % make e2e
./hack/test.sh "./e2e/..." 30m
go run ./hack/../vendor/github.com/onsi/ginkgo/v2/ginkgo -r -v --randomize-all --randomize-suites --keep-going --race --trace --timeout=30m ./e2e/...
Running Suite: Cluster API Suite - /Users/karthikkn/capi-test/cluster-capi-operator/e2e
=======================================================================================
Random Seed: 1687864170 - will randomize all specs

Will run 3 of 3 specs
------------------------------
[BeforeSuite]
/Users/karthikkn/capi-test/cluster-capi-operator/e2e/e2e_test.go:48
[BeforeSuite] PASSED [1.400 seconds]
------------------------------
Cluster API IBMPowerVS MachineSet should be able to run a machine
/Users/karthikkn/capi-test/cluster-capi-operator/e2e/powervs_test.go:52
  STEP: Creating core cluster @ 06/27/23 16:39:41.117
  STEP: Creating IBMPowerVSCluster cluster @ 06/27/23 16:39:42.011
  STEP: Creating IBMPowerVS machine template @ 06/27/23 16:39:43.131
  STEP: Creating MachineSet "ibmpowervs-machineset" @ 06/27/23 16:39:43.4
  STEP: Waiting for MachineSet machines "ibmpowervs-machineset" to enter Running phase @ 06/27/23 16:39:43.752
  STEP: Deleting MachineSet "ibmpowervs-machineset" @ 06/27/23 17:01:20.321
  STEP: Waiting for MachineSet "ibmpowervs-machineset" to be deleted @ 06/27/23 17:01:20.6
  STEP: Deleting /powervs-machine-template @ 06/27/23 17:02:18.746
• [1357.858 seconds]
------------------------------
Cluster API AWS MachineSet should be able to run a machine with a default provider spec
/Users/karthikkn/capi-test/cluster-capi-operator/e2e/aws_test.go:60
  [SKIPPED] in [BeforeAll] - /Users/karthikkn/capi-test/cluster-capi-operator/e2e/aws_test.go:41 @ 06/27/23 17:02:18.982
  [SKIPPED] in [AfterEach] - /Users/karthikkn/capi-test/cluster-capi-operator/e2e/aws_test.go:53 @ 06/27/23 17:02:18.983
S [SKIPPED] [0.001 seconds]
Cluster API AWS MachineSet [BeforeAll] should be able to run a machine with a default provider spec
  [BeforeAll] /Users/karthikkn/capi-test/cluster-capi-operator/e2e/aws_test.go:39
  [It] /Users/karthikkn/capi-test/cluster-capi-operator/e2e/aws_test.go:60

  [SKIPPED] Skipping AWS E2E tests
  In [BeforeAll] at: /Users/karthikkn/capi-test/cluster-capi-operator/e2e/aws_test.go:41 @ 06/27/23 17:02:18.982

  Full Stack Trace
    github.com/openshift/cluster-capi-operator/e2e.glob..func1.1()
    	/Users/karthikkn/capi-test/cluster-capi-operator/e2e/aws_test.go:41 +0x10c
------------------------------
Cluster API GCP MachineSet should be able to run a machine
/Users/karthikkn/capi-test/cluster-capi-operator/e2e/gcp_test.go:50
  [SKIPPED] in [BeforeAll] - /Users/karthikkn/capi-test/cluster-capi-operator/e2e/gcp_test.go:32 @ 06/27/23 17:02:18.989
  [SKIPPED] in [AfterEach] - /Users/karthikkn/capi-test/cluster-capi-operator/e2e/gcp_test.go:43 @ 06/27/23 17:02:18.99
S [SKIPPED] [0.001 seconds]
Cluster API GCP MachineSet [BeforeAll] should be able to run a machine
  [BeforeAll] /Users/karthikkn/capi-test/cluster-capi-operator/e2e/gcp_test.go:30
  [It] /Users/karthikkn/capi-test/cluster-capi-operator/e2e/gcp_test.go:50

  [SKIPPED] Skipping GCP E2E tests
  In [BeforeAll] at: /Users/karthikkn/capi-test/cluster-capi-operator/e2e/gcp_test.go:32 @ 06/27/23 17:02:18.989

  Full Stack Trace
    github.com/openshift/cluster-capi-operator/e2e.glob..func3.1()
    	/Users/karthikkn/capi-test/cluster-capi-operator/e2e/gcp_test.go:32 +0xed
------------------------------

Ran 1 of 3 Specs in 1359.268 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 2 Skipped
```

**Comment by Karthik-K-N** [comment]
@damdo Can this be merged

**Comment by damdo** [comment]
Not yet but shortly, we need to coordinate the merges with the other providers.

**Review by JoelSpeed — COMMENTED** [review]
/approve
/lgtm
/retest

**Pull request merged**
