### PR TITLE
OCPCLOUD-2624: Merge https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud:v0.8.0 (8cd12b5) into main

### PR DESCRIPTION
**Pull request by damdo**

### CODE REVIEW

**Comment by damdo** [comment]
/hold
For testing

**Comment by Karthik-K-N** [comment]
Thank you, I will test and update here with test results.

**Comment by Karthik-K-N** [comment]
Created a cluster which used Cluserapi rather than terraform using CutsomNoupgrade featuregate, So not able to enable Techprieview feature gate, so manually applied the manifests from cluster-capi-repository and capibm repository

Replaced capibm and capi images by building a latest image from respective repos,

Could see pods running
```
% oc get pods -n openshift-cluster-api
NAME                                               READY   STATUS             RESTARTS   AGE
capi-controller-manager-6ff6478fbd-94hfk           1/1     Running            0          4h7m
capi-ibmcloud-controller-manager-d95767c86-9ll4f   2/2     Running            0          126m
```
Running latest version of capibm
```
I0527 14:33:26.676201   65997 capi_installer_controller.go:118] "processing CAPI provider ConfigMap" logger="CapiInstallerController" controller="clusteroperator" controllerGroup="config.openshift.io" controllerKind="ClusterOperator" ClusterOperator="cluster-api" namespace="" name="cluster-api" reconcileID="255171da-10ef-466e-a875-a72dce9ea30f" configmapName="ibmcloud" providerType="infrastructure" providerName="ibmcloud" providerVersion="v0.8.0"
```


Able to run e2e which creates cluster, machine so on
```
% oc -n openshift-cluster-api get cluster
NAME                         CLUSTERCLASS   PHASE          AGE   VERSION
rdr-hamzy-test-dal10-77t8b                  Provisioning   15m

% oc -n openshift-cluster-api get ibmpowervscluster
NAME                         CLUSTER                      AGE
rdr-hamzy-test-dal10-77t8b   rdr-hamzy-test-dal10-77t8b   6m7s

% oc -n openshift-cluster-api get machine
NAME                          CLUSTER                      NODENAME   PROVIDERID                                                     PHASE         AGE     VERSION
ibmpowervs-machineset-kcvlx   rdr-hamzy-test-dal10-77t8b              ibmpowervs://dal/dal10//ec15c8ef-3590-405c-90d1-1db432b83d5a   Provisioned   5m45s

% oc -n openshift-cluster-api get ibmpowervsmachine
NAME                             CLUSTER                      AGE     READY   STATE    HEALTH
powervs-machine-template-q9tc2   rdr-hamzy-test-dal10-77t8b   5m54s   true    ACTIVE   WARNING

```

**Review by Karthik-K-N — APPROVED** [review]
/lgtm

**Comment by damdo** [comment]
Awesome! Thank you!

/assign @JoelSpeed @nrb 

This is ready for approval now

/unhold

**Pull request merged**
