### PR TITLE
Bug 2042711: [OCPCLOUD-1268] Migrate Machine API to openshift/api

### PR DESCRIPTION
**Pull request by JoelSpeed**
We have moved the API definitions for Machine API to the openshift/api repository. They are no longer hosted in Machine-API-operator.

To enable this repo to keep up to date with the latest changes in the MAO repo, we need to migrate the API definitions over to the new location.

### CODE REVIEW

**Comment by damdo** [comment]
As part of the dependency bump to `1.23` we should be able to bump also this one: https://github.com/JoelSpeed/cluster-api-provider-ibmcloud/blob/8686975fa4495a9b101a9bff287a8579a6e94ad9/hack/fetch-ext-bins.sh#L30-L31

By looking at what tools versions are released here: https://storage.googleapis.com/kubebuilder-tools/ we should be able to use `1.23.1`.

**Review by elmiko — COMMENTED** [review]
/approve

**Comment by JoelSpeed** [comment]
/skip

We will merge this once 4.11 opens, for now, skipping to prevent retests

**Comment by JoelSpeed** [comment]
Have attached a bug to this because we need to update the MAO dependency to allow machine deletion hooks to operate on IBM. This means the whole migration is needed unforunately.

**Pull request merged**
