### PR TITLE
OCPBUGS-6418: Merge https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud:v0.4.0 (7399387) into main

### PR DESCRIPTION
**Pull request by damdo**
This PR merges upstream's https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud:v0.4.0 (7399387) into `main`.
Check [this comment](https://github.com/openshift/cluster-capi-operator/pull/101#issue-1564195291) for this CAPI provider bump testing status.

### CODE REVIEW

**Comment by damdo** [comment]
cc. @Karthik-K-N moved the rebase here.

This should be testable in combination with:
- https://github.com/openshift/cluster-capi-operator/pull/101
  - dev image: `quay.io/ddonati/cluster-capi-operator:pr101`
- https://github.com/openshift/cluster-api/pull/167
  - dev image: `quay.io/ddonati/cluster-api:release-1.3-eb18352e9-ocp-b1ff0acc0`
- https://github.com/openshift/cluster-api-provider-ibmcloud/pull/48"
  - dev image: `quay.io/ddonati/cluster-api-provider-ibmcloud:v0.4.0-1133ec4b-ocp-f1bdc301`
  
I linked here also container images so we can more easily spin up an IBM cluster with them. Would you be able to give it a try? For example running https://github.com/openshift/cluster-capi-operator/blob/main/e2e/powervs_test.go? Thanks!

**Comment by Karthik-K-N** [comment]
> cc. @Karthik-K-N moved the rebase here.
> 
> This should be testable in combination with:
> 
>     * [OCPBUGS-6377: Bump CAPI, CAPI providers, go 1.19 cluster-capi-operator#101](https://github.com/openshift/cluster-capi-operator/pull/101)
>       
>       * dev image: `quay.io/ddonati/cluster-capi-operator:pr101`
> 
>     * [Merge https://github.com/kubernetes-sigs/cluster-api:release-1.3 (eb18352) into master cluster-api#167](https://github.com/openshift/cluster-api/pull/167)
>       
>       * dev image: `quay.io/ddonati/cluster-api:release-1.3-eb18352e9-ocp-b1ff0acc0`
> 
>     * [OCPBUGS-6418: Merge https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud:v0.4.0 (7399387) into main #48](https://github.com/openshift/cluster-api-provider-ibmcloud/pull/48)"
>       
>       * dev image: `quay.io/ddonati/cluster-api-provider-ibmcloud:v0.4.0-1133ec4b-ocp-f1bdc301`
> 
> 
> I linked here also container images so we can more easily spin up an IBM cluster with them. Would you be able to give it a try? For example running https://github.com/openshift/cluster-capi-operator/blob/main/e2e/powervs_test.go? Thanks!

Sure, I will do the necessary testing, There are some api changes as well so will submit the necessary PRs for that.

**Comment by damdo** [comment]
We already have a PR where we bump all the go imports for the cluster-capi-operator here.
We should probably bump them on that PR:
- https://github.com/openshift/cluster-capi-operator/pull/101/files#diff-ad517cc0d74b9310c160a7a6456a05f8a0a9ba62661ca31b1d17bd9156e55a90R23-R24
- https://github.com/openshift/cluster-capi-operator/pull/101/files#diff-ad517cc0d74b9310c160a7a6456a05f8a0a9ba62661ca31b1d17bd9156e55a90R18

**Comment by damdo** [comment]
Hey @Karthik-K-N have you got the chance look at this? Let me know if I can help in any way. Thanks!

**Comment by Karthik-K-N** [comment]
> Hey @Karthik-K-N have you got the chance look at this? Let me know if I can help in any way. Thanks!

Hi @damdo I am trying to test it from couple days but failing to get cluster for some reasons, I update you as soon as possible. Thanks

**Review by elmiko — COMMENTED** [review]
/lgtm

leaving off approve for @Karthik-K-N to have a chance for further comment

**Comment by Karthik-K-N** [comment]
I have tested it and it works as expected

/lgtm

**Comment by Karthik-K-N** [comment]
@mkumatag can we merge this, as https://github.com/openshift/cluster-capi-operator/commit/a1a3bdbc81b7109a15b9070cac3deed1ef59ce55 merged, I can submit a PR to update manifests in capi-operator.

**Review by mkumatag — APPROVED** [review]

**Pull request merged**
