### PR TITLE
OCPBUGS-12895: Update IBM Packages

### PR DESCRIPTION
**Pull request by Karthik-K-N**
Updating IBM packages to fix vulnerabilities

CVE - https://pkg.go.dev/vuln/GO-2023-1571

Fixes: https://issues.redhat.com/browse/OCPBUGS-12615

### CODE REVIEW

**Comment by damdo** [comment]
Thanks for putting this together @Karthik-K-N 
We looks good but we will need to prefix the commit with `UPSTREAM: <carry>: `

**Comment by Karthik-K-N** [comment]
> Thanks for putting this together @Karthik-K-N We looks good but we will need to prefix the commit with `UPSTREAM: <carry>: `

Sure, I have updated commit message accordingly

**Review by damdo — COMMENTED** [review]
Thanks!
/approve

**Comment by mkumatag** [comment]
@Karthik-K-N can you please patch release-4.13 branch with the go.mod updates for https://issues.redhat.com/browse/OCPBUGS-12615

**Pull request merged**
