### PR TITLE
OCPBUGS-37369: UPSTREAM: <carry>: Fix go-retryablehttp CVE - 4.17

### PR DESCRIPTION
**Pull request by Karthik-K-N**

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by Karthik-K-N** [comment]
@JoelSpeed could you please help with required labels.

**Comment by JoelSpeed** [comment]
@Karthik-K-N Are you sure you have the correct bug number, I cannot seem to view it

**Comment by Karthik-K-N** [comment]
Yeah, Its correct, Even I had issues earlier viewing them but now I got access, Also I see I`BM Confidential Group` in contributing groups in Jira, may be thats the reason?

**Comment by JoelSpeed** [comment]
Without seeing the bug chain, I can't verify what is expected here. Where is the 4.18 bug? Is the 4.18 bug in the verified state? Which QE has verified the 4.18 version of this bug?

**Comment by Karthik-K-N** [comment]
> Without seeing the bug chain, I can't verify what is expected here. Where is the 4.18 bug? Is the 4.18 bug in the verified state? Which QE has verified the 4.18 version of this bug?

Let me try to get more info about it.

@prb112 could you please help.

**Comment by prb112** [comment]
You'll want to rename OCPBUGS-37369 to OCPBUGS-36079 most likely. I opened a ticket with JIRA to get access.

**Comment by prb112** [comment]
I've fixed the access for Joel
- [OCPBUGS-36076](https://issues.redhat.com/browse/OCPBUGS-36076) - [openshift-4.13.z]
- [OCPBUGS-36077](https://issues.redhat.com/browse/OCPBUGS-36077) - [openshift-4.14.z]
- [OCPBUGS-36078](https://issues.redhat.com/browse/OCPBUGS-36078) - [openshift-4.15.z]
- [OCPBUGS-37369](https://issues.redhat.com/browse/OCPBUGS-37369) - [openshift-4]

**Comment by JoelSpeed** [comment]
@Karthik-K-N I can't see a link between the 4.17 bug and a 4.18 version of the bug, we need to make sure this is resolved in 4.18 before we can backport to 4.17, do you have a 4.18 fix?

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N I can't see a link between the 4.17 bug and a 4.18 version of the bug, we need to make sure this is resolved in 4.18 before we can backport to 4.17, do you have a 4.18 fix?

Could of things need opinion on
1. I am not able to find Jira tickets for 4.16 and 4.18, So planning to clone the existing tickets
2. For 4.18 the module is updated in [upstream](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/go.mod#L113) and there is downstream rebase expected sometime last week or this week. So should I wait for this rebase or submit a PR with fix?

**Comment by JoelSpeed** [comment]
> I am not able to find Jira tickets for 4.16 and 4.18, So planning to clone the existing tickets

Cloning is fine as long as you link them all together in the right chain ordering

> For 4.18 the module is updated in [upstream](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/go.mod#L113) and there is downstream rebase expected sometime last week or this week. So should I wait for this rebase or submit a PR with fix?

It was updated in https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/commit/392efd0cc46eed34e0665919123d2ffed7a59bd1, so, if you want to bring this in earlier to avoid blocking the backports, you can, you just need to prefix the commit with `UPSTREAM: 1857:`

**Comment by Karthik-K-N** [comment]
> > I am not able to find Jira tickets for 4.16 and 4.18, So planning to clone the existing tickets
> 
> Cloning is fine as long as you link them all together in the right chain ordering
> 
> > For 4.18 the module is updated in [upstream](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/main/go.mod#L113) and there is downstream rebase expected sometime last week or this week. So should I wait for this rebase or submit a PR with fix?
> 
> It was updated in [kubernetes-sigs/cluster-api-provider-ibmcloud@392efd0](https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/commit/392efd0cc46eed34e0665919123d2ffed7a59bd1), so, if you want to bring this in earlier to avoid blocking the backports, you can, you just need to prefix the commit with `UPSTREAM: 1857:`

sure will do that.

**Comment by Karthik-K-N** [comment]
Submitted a PR for main https://github.com/openshift/cluster-api-provider-ibmcloud/pull/91

**Comment by Karthik-K-N** [comment]
main branch PR has been merged: https://github.com/openshift/cluster-api-provider-ibmcloud/pull/91

**Comment by JoelSpeed** [comment]
The 4.18 fix must be verified by QE before we can move this one along

**Comment by Karthik-K-N** [comment]
@juliemathew not sure how its verified, Could you please help us here.

**Comment by JoelSpeed** [comment]
/label backport-risk-assessed

The 4.18 bug has been moved to verified, 4.17 bug is filed correctly, will manually add valid jira labels

**Pull request merged**
