### PR TITLE
Bug 2036993: update repo for golang 1.17

### PR DESCRIPTION
**Pull request by elmiko**
This change updates the go.mod, Dockerfile, Makefile, and
ci-operator.yaml file to use golang 1.17, it also updates the vendor
directory.

### CODE REVIEW

**Comment by elmiko** [comment]
release repo update, https://github.com/openshift/release/pull/24671

**Review by Fedosin — APPROVED** [review]
/lgtm

IBM e2e job fails, I hope it will be fixed soon.

**Comment by JoelSpeed** [comment]
/hold

This is endlessly retesting as the IBM e2e is not working correctly. We will need a bug if we want to merge this update within 4.10.

@elmiko could you please decide on an appropriate path forward with this

**Comment by elmiko** [comment]
@JoelSpeed yup, i'll follow up with ibm and get a bug linked here

**Comment by elmiko** [comment]
/retitle Bug 2036993: update repo for golang 1.17

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-ibmcloud

Had a discussion with @cjschaef on slack, the IBM e2e is not stable at the moment so we cannot block PRs on it. We are going to make it optional going forward until the stability is improved

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-ibmcloud

Not sure if the previous was in error, will try again

**Pull request merged**
