### PR TITLE
Merge https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud:v0.4.0-alpha.3 (c88394b) into main

### PR DESCRIPTION
**Pull request by damdo**
This PR merges upstream's https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud:v0.4.0-alpha.3 (c88394b) into `master`.

Check [this comment](https://github.com/openshift/cluster-capi-operator/pull/101#issue-1564195291) for this CAPI provider bump testing status.

### CODE REVIEW

**Comment by damdo** [comment]
For coordination with other CAPI components:

/hold

**Comment by damdo** [comment]
The `generate` job is failing here.
Although is passing locally on my machine while sitting on this branch:

```
[~ git:(rebase-atop-v0.4.0-alpha.3)] $ make generate
/Library/Developer/CommandLineTools/usr/bin/make generate-go generate-modules generate-manifests generate-go-deepcopy generate-go-conversions
go generate ./...
go mod tidy
go: downloading github.com/IBM/go-sdk-core/v5 v5.12.0
go: downloading k8s.io/client-go v0.25.0
go: downloading github.com/IBM-Cloud/power-go-client v1.2.2
go: downloading github.com/IBM/vpc-go-sdk v0.30.0
go: downloading github.com/IBM/platform-services-go-sdk v0.31.4
go: downloading github.com/golang-jwt/jwt v3.2.2+incompatible
go: downloading sigs.k8s.io/cluster-api/test v1.3.2
go: downloading github.com/go-openapi/strfmt v0.21.3
go: downloading gopkg.in/go-playground/validator.v9 v9.31.0
go: downloading github.com/hashicorp/go-retryablehttp v0.7.1
go: downloading k8s.io/component-base v0.25.0
go: downloading github.com/go-openapi/runtime v0.23.0
go: downloading github.com/apparentlymart/go-cidr v1.1.0
go: downloading github.com/go-openapi/errors v0.20.2
go: downloading github.com/go-openapi/validate v0.20.3
go: downloading k8s.io/apiserver v0.25.0
go: downloading github.com/hashicorp/go-hclog v1.2.0
go: downloading github.com/oklog/ulid v1.3.1
go: downloading go.mongodb.org/mongo-driver v1.10.0
go: downloading k8s.io/cluster-bootstrap v0.25.0
go: downloading cloud.google.com/go/compute v1.7.0
go: downloading github.com/go-playground/universal-translator v0.18.0
go: downloading github.com/leodido/go-urn v1.2.1
go: downloading github.com/go-playground/locales v0.14.0
go: downloading gopkg.in/go-playground/assert.v1 v1.2.1
go: downloading github.com/opentracing/opentracing-go v1.2.0
go: downloading github.com/go-openapi/analysis v0.21.2
go: downloading github.com/go-openapi/loads v0.21.1
go: downloading github.com/go-openapi/spec v0.20.4
go: downloading github.com/coredns/caddy v1.1.0
go: downloading github.com/moby/term v0.0.0-20210619224110-3f7ff695adc6
go: downloading github.com/google/cel-go v0.12.4
go: downloading google.golang.org/genproto v0.0.0-20220616135557-88e70c0c3a90
go: downloading github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20220418222510-f25a4f6275ed
cd hack/tools; go mod tidy
hack/tools/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
hack/tools/bin/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role paths="./..." output:crd:artifacts:config=config/crd/bases
hack/tools/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/Library/Developer/CommandLineTools/usr/bin/make clean-generated-conversions SRC_DIRS="./api/v1beta1"
(IFS=','; for i in ./api/v1beta1; do find $i -type f -name 'zz_generated.conversion*' -exec rm -f {} \;; done)
hack/tools/bin/conversion-gen \
                --input-dirs=./api/v1beta1 \
                --build-tag=ignore_autogenerated_core \
                --output-file-base=zz_generated.conversion --output-base=. \
                --go-header-file=./hack/boilerplate/boilerplate.generatego.txt
[~ git:(rebase-atop-v0.4.0-alpha.3)] $ echo $?
0
```

**Comment by Karthik-K-N** [comment]
HI @damdo , I will take a look, Thank you

**Comment by Karthik-K-N** [comment]
We got a new release https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/releases/tag/v0.4.0, Can we directly upgrade to this.

**Comment by damdo** [comment]
Ah nice! Thanks @Karthik-K-N, I'll change the PR to sit on top of the newest release.

**Comment by damdo** [comment]
Superseded by https://github.com/openshift/cluster-api-provider-ibmcloud/pull/47

**Pull request closed without merging**
