### PR TITLE
OCPBUGS-36077: UPSTREAM: <carry>: Fix go-retryablehttp CVE - 4.14

### PR DESCRIPTION
**Pull request by Karthik-K-N**

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
@damdo could you please help.

**Review by damdo — COMMENTED** [review]
/approve
/lgtm

**Comment by damdo** [comment]
@Karthik-K-N the bug reference looks incorrect

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N the bug reference looks incorrect

Updated it now,earlier missed one 7 in OCPBUGS-36077

**Comment by damdo** [comment]
It looks like it can't find it 🤔

**Comment by Karthik-K-N** [comment]
Are you able to view to now, There is used to be some issue with me accessing the Jira and got some permission to view them.

**Comment by damdo** [comment]
@Karthik-K-N I can now thanks, but Github Jira bot can't.

**Comment by Karthik-K-N** [comment]
Previous merged PRs also had the same issue but it worked https://github.com/openshift/cluster-api-provider-ibmcloud/pull/89#issuecomment-2429331960

**Comment by damdo** [comment]
Ok thanks. cc. @sunzhaohua2 for label

**Comment by damdo** [comment]
@Karthik-K-N it looks like last time Joel added the label manually
https://github.com/openshift/cluster-api-provider-ibmcloud/pull/87#issuecomment-2471846002

**Comment by damdo** [comment]
/assign @JoelSpeed 
For manual labelling of the jira/valid-bug

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N it looks like last time Joel added the label manually [#87 (comment)](https://github.com/openshift/cluster-api-provider-ibmcloud/pull/87#issuecomment-2471846002)

Oh yeah correct, I forgot. Thanks

**Comment by JoelSpeed** [comment]
Manually checked on the bug requirements

**Pull request merged**
